# -*- coding: utf-8 -*-
"""EPIC_LSTM_Parallel_Multivariate_diff.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1w3PnIeWZsqQbY_tgActIPNjZ1LJTk4Gd

## Setup
"""

#from google.colab import drive
#drive.mount('/content/gdrive/')
#path = 'gdrive/MyDrive/ColabOutput/'

path = './'

# Commented out IPython magic to ensure Python compatibility.
import math
import os
from itertools import product

import numpy as np
from numpy import array

import pandas as pd

import matplotlib.pyplot as plt

import seaborn as sns

import scipy.stats as scs

from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error
from sklearn import preprocessing

import statsmodels.api as sm
import statsmodels.formula.api as smf
import statsmodels.tsa.api as smt
from statsmodels.graphics.tsaplots import plot_acf , plot_pacf
from statsmodels.tsa.stattools import acf, pacf, grangercausalitytests, adfuller
from statsmodels.tsa.statespace.sarimax import SARIMAX
from statsmodels.tsa.statespace.varmax import VARMAX


import joblib

import tensorflow as tf
from tqdm.keras import TqdmCallback
from tqdm import tqdm_notebook


import warnings
warnings.filterwarnings('ignore')


# %matplotlib inline
plt.rcParams['figure.figsize'] = [10, 7.5]

seed = 7
np.random.seed(seed)

"""### Healper Functions

## Dataset
"""

all_19_oct_data = []

url_prefix = "https://raw.githubusercontent.com/JayPBhatia/MastersProject/main/data/itrust/"
# 
epic_19_oct_data_files = ["EpicLog_Scenario_1_19_Oct_2018_14_44.csv", 
                   "EpicLog_Scenario_2_19_Oct_2018_14_56.csv", 
                   "EpicLog_Scenario_3_19_Oct_2018_15_02.csv", 
                   "EpicLog_Scenario_4_19_Oct_2018_15_23.csv", 
                   "EpicLog_Scenario_5_19_Oct_2018_15_45.csv", 
                   "EpicLog_Scenario_6_19_Oct_2018_16_06.csv"]

for filename in epic_19_oct_data_files:
    file_df = pd.read_csv(url_prefix+filename, index_col=None, header=0)
    all_19_oct_data.append(file_df)

df = pd.concat(all_19_oct_data, axis=0, ignore_index=True)
df['Timestamp'] = pd.to_datetime(df['Timestamp'], infer_datetime_format=True)
df = df.drop_duplicates(subset='Timestamp', keep="last")
df = df.set_index('Timestamp')
df = df.filter(regex='Generation.GIED1.Measurement')
df

df.describe().transpose()

df.info()

df_org = df.copy()
df = df.diff().dropna().reset_index(drop=True)
df

df_org['Generation.GIED1.Measurement.Apparent'].plot(figsize=(35,5))

df['Generation.GIED1.Measurement.Apparent'].plot(figsize=(35,5))

print("*****************************************    training model for :  ********************************************")
df_new = df.copy().reset_index(drop=True)
n = len(df_new)
train_df = df_new[0:int(n*0.85)].copy()
val_df = df_new[int(n*0.85):int(n*0.95)].copy()
test_df = df_new[int(n*0.95):].copy()

print("train_df shape : ", train_df.shape)
print("val_df shape : ", val_df.shape)
print("test_df shape : ", test_df.shape)

train_df.head(5)

train_df[32:33]

test_df.tail(5)

scaler = preprocessing.MinMaxScaler()
scaler.fit(train_df)
scaler_filename = path + "scaler.save"
joblib.dump(scaler, scaler_filename) 


train_df_scaled = train_df.copy()
train_df_scaled = pd.DataFrame(scaler.transform(train_df))
print("train_df_scaled shape : ", train_df_scaled.shape)

val_df_scaled = val_df.copy()
val_df_scaled = pd.DataFrame(scaler.transform(val_df))
print("val_df_scaled shape : ", val_df_scaled.shape)

test_df_scaled = test_df.copy()
test_df_scaled = pd.DataFrame(scaler.transform(test_df))
print("test_df_scaled shape : ", test_df_scaled.shape)

n_steps = 32
def split_sequences(sequences, n_steps):
	X, y = list(), list()
	for i in range(len(sequences)):
		# find the end of this pattern
		end_ix = i + n_steps +1
		# check if we are beyond the dataset
		if end_ix > len(sequences):
			break
		# gather input and output parts of the pattern
		seq_x, seq_y = sequences[i:end_ix-1, :], sequences[end_ix-1, :]
		X.append(seq_x)
		y.append(seq_y)
	return array(X), array(y)
 
X_train, y_train = split_sequences(train_df_scaled.values, n_steps)
X_val, y_val = split_sequences(val_df_scaled.values, n_steps)
X_test, y_test = split_sequences(test_df_scaled.values, n_steps)

print("X_train shape: ", X_train.shape, " y_train shape: ", y_train.shape)
print("X_val shape: ", X_val.shape, " y_val shape: ", y_val.shape)
print("X_test shape: ", X_test.shape, " y_test shape: ", y_test.shape)

pd.DataFrame(scaler.inverse_transform(X_train[0]))

pd.DataFrame(scaler.inverse_transform(y_train)).head(1)

# Prepare the training dataset
train_dataset = tf.data.Dataset.from_tensor_slices((X_train, y_train))
train_dataset = train_dataset.shuffle(buffer_size=64).batch(256)

# Prepare the validation dataset
val_dataset = tf.data.Dataset.from_tensor_slices((X_val, y_val))
val_dataset = val_dataset.batch(64)

lstm_model = tf.keras.models.Sequential()
lstm_model.add(tf.keras.layers.Bidirectional( tf.keras.layers.LSTM(64, input_shape=(X_train.shape[1], X_train.shape[2]))))
lstm_model.add(tf.keras.layers.Dense(y_train.shape[1]))
lstm_model.compile(optimizer=tf.optimizers.Adam(), loss=tf.losses.MeanSquaredError(), #loss=tf.keras.losses.Huber(delta=1.35), 
              metrics=["mae", "mse", "msle", "logcosh", tf.keras.metrics.RootMeanSquaredError()])
early_stoppong_callback = tf.keras.callbacks.EarlyStopping(monitor='val_mae', mode='min', patience=64)
tqdm_callback = TqdmCallback(verbose=1)
history = lstm_model.fit(train_dataset, validation_data=val_dataset, epochs=512, validation_steps=4, callbacks=[early_stoppong_callback, tqdm_callback ], verbose=0)
lstm_model.save(path + 'epic_lstm_model.h5')

def plot_history(history, key):
  plt.plot(history.history[key][20:])
  plt.plot(history.history['val_'+key][20:])
  plt.xlabel("Epochs")
  plt.ylabel(key)
  plt.legend([key, 'val_'+key])
  plt.show()
plt.figure(figsize=(20,5))
plot_history(history, 'mse')
plt.figure(figsize=(20,5))
plot_history(history, 'mae')

y_pred=lstm_model.predict(X_test)
y_test_inv = pd.DataFrame(scaler.inverse_transform(y_test))
y_pred_inv = pd.DataFrame(scaler.inverse_transform(y_pred))

for i, col in enumerate(df.columns):

  h = tf.keras.losses.Huber()
  print(col + " huber loss : ", h(y_test_inv[i], y_pred_inv[i]).numpy())
  print(col + " std : ", df[col].describe().loc[['std']][0])

  plt.figure(figsize=(30,5))
  plt.plot(abs(y_pred_inv[i] - y_test_inv[i]), color='black')
  plt.show()
  plt.figure(figsize=(30,5))
  plt.plot(y_pred_inv[i], color='red')
  plt.plot(y_test_inv[i], color='green')
  plt.show()

url_prefix = "https://raw.githubusercontent.com/JayPBhatia/MastersProject/main/data/itrust/"
# 
epic_data_files = ["EpicLog_Scenario_7_07_Nov_2018_14_40.csv", 
                   "EpicLog_Scenario_8_07_Nov_2018_14_57.csv"]

for epic_file in epic_data_files:
  print("*****************************************    evaluate model for : " , epic_file , " : " , col , "    ********************************************")
  # move label col to last 
  df_eval = pd.read_csv(url_prefix+epic_file)
  df_eval = df_eval.filter(regex='Generation.GIED1.Measurement')
  print("df_eval.shape ", df_eval.shape)

  df_eval_new = df_eval.diff()
  df_eval_new = df_eval_new.dropna()

  new_scaler = joblib.load(path + 'scaler.save')
  new_lstm_model = tf.keras.models.load_model(path + 'epic_lstm_model.h5')

  df_eval_scaled = df_eval_new.copy()  
  df_eval_scaled = pd.DataFrame(new_scaler.transform(df_eval_new))

  X_eval, y_eval = split_sequences(df_eval_scaled.values, n_steps)
  print("X_eval.shape ", X_eval.shape)
  print("y_eval.shape ", y_eval.shape)

  result = new_lstm_model.evaluate(X_eval, y_eval, verbose=0)
  print(col ," result  : " , result)

  y_eval_pred = new_lstm_model.predict(X_eval)
  y_eval_inv = pd.DataFrame(new_scaler.inverse_transform(y_eval))
  y_eval_pred_inv = pd.DataFrame(new_scaler.inverse_transform(y_eval_pred))



  for i, col in enumerate(df.columns):

    h = tf.keras.losses.Huber()
    print(col + " huber loss : ", h(y_eval_inv[i], y_eval_pred_inv[i]).numpy())
    print(col + " std : ", df[col].describe().loc[['std']][0])

    plt.figure(figsize=(30,5))
    plt.plot(abs(y_eval_pred_inv[i] - y_eval_inv[i]), color='black')
    plt.show()
    plt.figure(figsize=(30,5))
    plt.plot(y_eval_pred_inv[i], color='red')
    plt.plot(y_eval_inv[i], color='green')
    plt.show()